# Setup
title: 雜物儲存室
tagline: "Coding Blog"
description: ""
url: https://davidyujia.github.io
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: David
  url: https://github.com/davidyujia
  email: davidyujia@gmail.com

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/html-coding.png"
      weight: 99
  - scope:
      path: "/_posts"
    values:
      layout: "post"
      image: "/assets/images/html-coding.png"

# Custom vars
google_analytics_id: G-M7V2WK818X

# Comments
disqus-shortname: davidyujia

# SEO
lang: zh_tw
logo: "/public/html-coding.png"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

# Gems
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
